import { Post } from "../../Interfaces/Interfaces"

const posts: Post[] = [
    {
      postId: 1,
      mediaFileName: "media1",
      mediaType:"image",
      postType: "Post",
      isLiked:true,
      isBookmarked:false,
      postDate: new Date("2023-12-01T12:00:00"),
      content: "Just completed my first marathon! 🏃‍♂️",
      like: 150,
      commentNum: 20,
      view: 1200,
      author: {
        name: "John Doe",
        username: "john_doe",
        userId: 101,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 2,
      postType: "Comment",
      isLiked:false,
      isBookmarked:false,
      postDate: new Date("2023-12-02T14:30:00"),
      content: "Amazing achievement! Congrats!",
      repliesTo: 1,
      like: 20,
      commentNum: 5,
      view: 100,
      author: {
        name: "Jane Smith",
        username: "jane_smith",
        userId: 102,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 3,
      postType: "Quote",
      isLiked:true,
      isBookmarked:true,
      postDate: new Date("2023-12-03T16:45:00"),
      content: "The journey of a thousand miles begins with one step. 🚶‍♀️",
      quotedFrom: 1,
      like: 80,
      commentNum: 10,
      view: 500,
      author: {
        name: "Alice Johnson",
        username: "alice_johnson",
        userId: 103,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 4,
      mediaFileName: "media4",
      mediaType:"image",
      isLiked:false,
      isBookmarked:false,
      postType: "Post",
      postDate: new Date("2023-12-04T10:15:00"),
      content: "Enjoying a beautiful sunset 🌅",
      like: 120,
      commentNum: 15,
      view: 800,
      author: {
        name: "Bob Martin",
        username: "bob_martin",
        userId: 104,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 5,
      postType: "Comment",
      isLiked:false,
      isBookmarked:false,
      postDate: new Date("2023-12-05T18:00:00"),
      content: "Stunning view! 😍",
      repliesTo: 4,
      like: 30,
      commentNum: 3,
      view: 200,
      author: {
        name: "Emma Wilson",
        username: "emma_wilson",
        userId: 105,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 6,
      mediaFileName: "media6",
      mediaType: "video",
      postType: "Quote",
      isLiked:false,
      isBookmarked:true,
      postDate: new Date("2023-12-06T12:00:00"),
      content: "Nature is the best artist 🌳",
      quotedFrom: 4,
      like: 50,
      commentNum: 8,
      view: 400,
      author: {
        name: "Chris Brown",
        username: "chris_brown",
        userId: 106,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 7,
      postType: "Post",
      isLiked:false,
      isBookmarked:false,
      postDate: new Date("2023-12-07T08:30:00"),
      content: "Finally learned to cook pasta 🍝",
      like: 90,
      commentNum: 12,
      view: 700,
      author: {
        name: "Diana Ross",
        username: "diana_ross",
        userId: 107,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 8,
      postType: "Comment",
      isLiked:true,
      isBookmarked:false,
      postDate: new Date("2023-12-08T09:45:00"),
      content: "Looks delicious! What recipe did you use?",
      repliesTo: 7,
      like: 10,
      commentNum: 2,
      view: 150,
      author: {
        name: "Edward White",
        username: "edward_white",
        userId: 108,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 9,
      postType: "Quote",
      isLiked:true,
      isBookmarked:false,
      postDate: new Date("2023-12-09T11:00:00"),
      content: "Cooking is a form of art! 🎨",
      quotedFrom: 7,
      like: 60,
      commentNum: 7,
      view: 350,
      author: {
        name: "Fiona Green",
        username: "fiona_green",
        userId: 109,
        profilePic: "https://via.placeholder.com/150",
      },
    },
    {
      postId: 10,
      postType: "Post",
      isLiked:false,
      isBookmarked:false,
      postDate: new Date("2023-12-10T15:20:00"),
      content: "Weekend vibes! 🌞",
      like: 200,
      commentNum: 25,
      view: 1500,
      author: {
        name: "George Harris",
        username: "george_harris",
        userId: 110,
        profilePic: "https://via.placeholder.com/150",
      },
    },
  ];
  
 
  


const useGetHomePost = () => {
    function fetchMorePosts(){
        console.log("hi")
    }

    return { page: 1, hasmore: false, data:posts , fetchMorePosts }
}

export default useGetHomePost